### ISSUE TITLE
wanted function

### ISSUE THREAD

**Issue by sineptic** [zesterer/chumsky#653]
Is there any function that read only if in input pattern occurs EXACTLY N times. existed function `exactly()` read even if there more than N occurs.

```rust
// This don't work:
let pattern = || {...};
let a = || read_until(pattern().repeated().exactly(N).then_ignore(pattern().not().rewind()));
```
```rust
// Example
let N = 2;
let pattern = || just::<_, Simple<_>>('a');
let a = ...;
assert!(a().parse("aaa ").is_ok());

//  ++-        +++
// "a̲aa " -> "aa̲a "
```
And I can't read already processed input.

**Comment by sineptic** [comment]
More general, I need function, that return only if pattern matches after not match.

I need matches equal number of backticks, but 
```
_```abc``_ matches with _`_ | _``abc``_
```

**Comment by sineptic** [comment]
I think to work it must be names smth like (`take`/`skip`)`_until_exactly`

**Comment by zesterer** [comment]
You can do `a.repeated().exactly(n).then_ignore(a.not())`.

The final part expects anything that *isn't* an `a` immediately after the repeating section, effectively preventing more than `n` instances ever occurring.

**Comment by zesterer** [comment]
That said, the pattern you are looking for (the backticks) is context-sensitive and won't be solved with this alone. See my response here about parsing Rust-like raw strings, which pretty much follow the same pattern: https://github.com/zesterer/chumsky/discussions/441#discussioncomment-9661605

**Comment by sineptic** [comment]
> You can do `a.repeated().exactly(n).then_ignore(a.not())`.
> 
> The final part expects anything that *isn't* an `a` immediately after the repeating section, effectively preventing more than `n` instances ever occurring.

It don't works with  my example

**Comment by zesterer** [comment]
Is this still an issue for you?

**Comment by sineptic** [comment]
Now I working on other projects, but I missed this feature. Only solution, that I found is to lex into tokens first(and group same pattern into 1 element)

So this issue still relevant.

**Comment by zesterer** [comment]
Going to close this since the original problem is solvable with chumsky. The specific problem mentioned is also solvable with context-sensitive parsers.
